# Generated by Django 3.2 on 2022-04-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='bookmark_reg_date',
            field=models.DateTimeField(blank=True, db_column='Bookmark_reg_date', null=True),
        ),
    ]
