# Generated by Django 3.2 on 2022-04-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_adj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adj',
            fields=[
                ('adj_id', models.AutoField(primary_key=True, serialize=False)),
                ('first', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'adj',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Noun',
            fields=[
                ('noun_id', models.AutoField(primary_key=True, serialize=False)),
                ('second', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'noun',
                'managed': True,
            },
        ),
    ]
