# Generated by Django 3.2 on 2022-04-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bookmark_bookmark_reg_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Searchpicture',
            fields=[
                ('searchpicture_id', models.AutoField(db_column='Searchpicture_id', primary_key=True, serialize=False)),
                ('searchpicture_url', models.CharField(db_column='Searchpicture_url', max_length=1000)),
            ],
            options={
                'db_table': 'searchpicture',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='authboard',
            name='ab_img_fir',
            field=models.CharField(blank=True, db_column='Ab_img_fir', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='authboard',
            name='ab_img_se',
            field=models.CharField(blank=True, db_column='Ab_img_se', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='authboard',
            name='ab_img_thi',
            field=models.CharField(blank=True, db_column='Ab_img_thi', max_length=1000, null=True),
        ),
    ]
