# Generated by Django 3.2 on 2022-04-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220429_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authboard',
            name='ab_img_fir',
            field=models.ImageField(blank=True, db_column='Ab_img_fir', null=True, upload_to='ab_images/'),
        ),
        migrations.AlterField(
            model_name='authboard',
            name='ab_img_se',
            field=models.ImageField(blank=True, db_column='Ab_img_se', null=True, upload_to='ab_images/'),
        ),
        migrations.AlterField(
            model_name='authboard',
            name='ab_img_thi',
            field=models.ImageField(blank=True, db_column='Ab_img_thi', null=True, upload_to='ab_images/'),
        ),
        migrations.AlterField(
            model_name='searchpicture',
            name='searchpicture_url',
            field=models.ImageField(db_column='Searchpicture_url', upload_to='search_images/'),
        ),
    ]
