# Generated by Django 3.2 on 2022-04-25 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_adj_noun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='user_account',
        ),
    ]
