# Generated by Django 3.2 on 2022-05-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220503_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_imgtag',
            field=models.ImageField(blank=True, db_column='Store_imgtag', null=True, upload_to='img_tag/'),
        ),
    ]
